name: diskonindonesia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  supabase_flutter: ^2.9.1
  google_fonts: ^6.1.0
  go_router: ^16.0.0
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  provider: ^6.1.5
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  http: ^1.4.0
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.6
  local_auth: ^2.3.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  camera: ^0.11.2
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.3.1
  firebase_messaging: ^15.2.10
  lottie: ^3.3.1
  flutter_animate: ^4.5.2
  confetti: ^0.8.0
  intl: ^0.20.2
  uuid: ^4.5.1
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  fl_chart: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
